### ISSUE TITLE
A couple of editorial comments

### ISSUE THREAD

**Issue by klausnielsen** [MagneticEarth/MagneticEarth.github.io#1]
Dear Ashley,

As promised in my email here are a few editorial comments on this excellent site.

1) On the **frontpage** IGRF-12 illustration it seems that the red levels of intensity are not represented in the scale. I might be reading it the wrong way but it is confusing.
![image](https://user-images.githubusercontent.com/3999584/70799954-4efc6b80-1dab-11ea-8c71-660489a45834.png)

2) In the table overview of **Geomagnetic Models** the asterisk connected with "Crustal grids" doesn't seem to point anywhere.
![image](https://user-images.githubusercontent.com/3999584/70800380-6720ba80-1dac-11ea-8dd2-1014e8983429.png)

3) And on the same sub page it seems the beginning of the sentence below the table is missing
![image](https://user-images.githubusercontent.com/3999584/70800519-c252ad00-1dac-11ea-93bb-c637a441d9ca.png)

Hope this might be useful.
Best,
Klaus Nielsen (DTU Space)

**Comment by smithara** [comment]
Thank you for your engagement and for noticing these things! I will fix them. I plan to re-use some of the writing I did for my thesis but it will need a bunch more condensing so your editorial input once those additions are live will be very welcome ;)

About the figure in point 1 - it's confusing because there are two things displayed. The contours show the magnetic declination (what you get on the mouse-over) and they are coloured red and blue. That only really shows up when they approach -90/90 near the poles. I'll have a think how to represent this more cleanly! For more figures showing different parts of the vector (and its changes in time), see (for example) http://www.geomag.bgs.ac.uk/education/earthmag.html#_Toc2075554

**Comment by klausnielsen** [comment]
Excellent, Ashley. I look forward to reading more and will be happy to send any feedback I might have.
For the figure an explanation like the one you give will be sufficient I think - makes good sense :)
Thanks for the link to BGS intro site. I will definitely look into this.

Best,
Klaus


Klaus Nielsen

Project coordinator, PhD



Mob.  +45 3023 7176

Dir.    +45 4525 9776

klausn@space.dtu.dk<mailto:klausn@space.dtu.dk>

Centrifugevej

Building 356

DK-2800 Kgs. Lyngby

www.space.dtu.dk<http://www.space.dtu.dk/>


________________________________

**Comment by smithara** [comment]
These issues have been fixed
